version: "0.5"

processes:
  backend:
    command: cd backend && ../.venv/bin/python -m uvicorn main:app --reload --host 0.0.0.0 --port 8000
    availability:
      restart: on_failure
    
  frontend:
    command: cd frontend && VITE_USE_MOCK=false npm run dev -- --host 0.0.0.0
    availability:
      restart: on_failure
    depends_on:
      backend:
        condition: process_started
  
  frontend-mock:
    command: cd frontend && VITE_USE_MOCK=true npm run dev -- --host 0.0.0.0
    availability:
      restart: on_failure
    disabled: true
